const actionType = {
  SET_CURRENCY: 'SET_CURRENCY',
  SET_CATEGORY: 'SET_CATEGORY',
  FETCH_CURRENCY: 'FETCH_CURRENCY',
  FETCH_CATEGORIES: 'FETCH_CATEGORY',
  FETCH_CATEGORY_PRODUCTS: 'FETCH_CATEGORY_PRODUCTS',
  FETCH_PRODUCT: 'FETCH_PRODUCT',
  FETCH_PRODUCT_PRICE: 'FETCH_PRODUCT_PRICE',
  ADD_TO_CART: 'ADD_TO_CART',
  CART_UPDATE_PRODUCT_QTY: 'CART_UPDATE_PRODUCT_QTY',
  GET_TOTAL: 'GET_TOTAL',
  GET_TOTAL_QTY: 'GET_TOTAL_QTY',
  TOGGLE_MINICART: 'TOGGLE_MINICART',
};
export default actionType;
