const actionType = {
  SET_CURRENCY: 'SET_CURRENCY',
  SET_CATEGORY: 'SET_CATEGORY',
  FETCH_CURRENCY: 'FETCH_CURRENCY',
  FETCH_CATEGORIES: 'FETCH_CATEGORY',
  FETCH_CATEGORY_PRODUCTS: 'FETCH_CATEGORY_PRODUCTS',
  FETCH_PRODUCT: 'FETCH_PRODUCT',
};
export default actionType;
